version: '3'

services:

  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace/mounted_volume
  test:
    build:
      context: .
      dockerfile: ./docker/test.Dockerfile
  serve:
    build:
      context: .
      dockerfile: ./docker/serve.Dockerfile
    ports:
      - "8080:8080"