data_path: "/leonardo_work/EUHPC_E03_068/marianna/laion_bvd_recap/datacomp_1b/recaptioned_tars"
output_dir: "/leonardo_work/EUHPC_E03_068/marianna/laion_bvd_recap/datacomp_1b/recaptioned_tars_short"
batch_size: 64
num_workers: 1
meta_key: "json"
img_key: "jpg"
make_visualization: false
save_tar: true
convert_to_tuples: false
mapper_functions: 
- type: add_fields
  input_key: "txt"
  output_key: "deepseek_caption"
  metadata_path: "/leonardo_work/EUHPC_E03_068/marianna/laion_bvd_recap/datacomp_1b/deepseek-ai/deepseek-vl2-tiny/short_caption"
  data_path: "/leonardo_work/EUHPC_E03_068/marianna/laion_bvd_recap/datacomp_1b/recaptioned_tars"

