# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 'test & train'
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
      - name: Lint with flake8 & black
        run: |
          make lint
      - name: Unit tests
        run: |
          make test
      - name: Regression e2e tests
        run: |
          make clean generate-dataset train
      - name: Coverage report
        run: |
          make coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v1

  train:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          make install
      - name: Train the model
        run: |
          make train
      - name: Archive training artifacts
        uses: actions/upload-artifact@v2
        with:
          name: models
          path: models

